import Link from "next/link";
import "../globals.css";
import { Noto_Sans_Thai } from "next/font/google";
import SideNavMainComponent from "@/components/side-nav/side-nav-server";
import { ClerkProvider, UserButton, currentUser } from "@clerk/nextjs";
import type { User } from "@clerk/nextjs/api";

const inter = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user: User | null = await currentUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className + " flex h-screen flex-col"}>
          <header>
            <div className="flex w-full bg-slate-300 p-2">
              <div className="flex w-full items-center justify-end gap-3 p-3">
                <Link
                  className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                  href={"/sales"}
                >
                  งานขาย
                </Link>
                <Link
                  className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                  href={"/account-receivable"}
                >
                  ลูกค้า
                </Link>
                <Link
                  className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                  href={"/purchase"}
                >
                  งานรับสินค้า
                </Link>
                <Link
                  className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                  href={"/account-payable"}
                >
                  เจ้าหนี้
                </Link>
                <Link
                  className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                  href={"/inventory"}
                >
                  ข้อมูลสินค้า
                </Link>
                <UserButton />
              </div>
            </div>
          </header>
          {!user?.privateMetadata.role && <Unauthorized></Unauthorized>}
          {!!user?.privateMetadata.role && (
            <div className="flex h-full w-full">
              <div className="w-full">{children}</div>
            </div>
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}

function Unauthorized() {
  return (
    <div className="text-center">
      <div className="w-full">Please Contact Admin to Access this page</div>
    </div>
  );
}
