import Link from "next/link";
import "./globals.css";
import { Noto_Sans_Thai } from "next/font/google";

const inter = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " flex h-screen flex-col"}>
        <header>
          <div className="flex w-full bg-slate-300 p-2">
            <div className="flex w-full items-center justify-end gap-3 p-3">
              <Link
                className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                href={"/sales"}>
                งานขาย
              </Link>
              <Link
                className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                href={"/account-receivable"}>
                ลูกค้า
              </Link>
              <Link
                className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                href={"/purchase"}>
                งานรับสินค้า
              </Link>
              <Link
                className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                href={"/account-payable"}>
                เจ้าหนี้
              </Link>
              <Link
                className="text-slate-700 hover:cursor-pointer hover:text-slate-600"
                href={"/inventory"}>
                ข้อมูลสินค้า
              </Link>
            </div>
          </div>
        </header>
        <div className="flex h-full w-full">
          <div className="h-full w-48 bg-slate-200 p-2">
            <ul className="flex flex-col items-center p-2">
              {/* <li>test</li>
              <li>test</li>
              <li>test</li>
              <li>test</li> */}
            </ul>
          </div>
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
